### ISSUE TITLE
Cleric Can’t see Enchants 

### ISSUE THREAD

**Issue by MasterBlast773** [apace100/origins-classes#21] opened 2021-02-24 22:35 UTC
When you are a cleric, they get better enchants, but they actually can’t see the enchants they are going to get, only the enchants that would show if you weren’t a cleric. This makes the second advantage of being a cleric useless, since you don’t actually know what you’re going to get.

**Comment by apace100** [comment] 2021-03-01 23:26
Duplicate of https://github.com/apace100/origins-classes/issues/20

**Closed as completed by apace100** 2021-03-01 23:26 UTC
